database:
  default:
    host: 'dacc_db'
    port: '5432'
    dbname: 'dacc'
    user: 'dacc'
    password: 'Secr3tP4ssw0rd'
  testing:
    host: 'dacc_db'
    port: '5432'
    dbname: 'dacc'
    user: 'dacc'
    password: 'Secr3tP4ssw0rd'
sentry:
  dsn: https://6fca9ff7c68944438d0c9799d19fcef2@errors.cozycloud.cc/5
  traces_sample_rate: 1.0
  environment: dev
logging:
  enable: False
  logger_criticity: debug
