"""empty message

Revision ID: 985bc36a9cbc
Revises: 5bafc336d30d
Create Date: 2022-02-11 15:34:55.199524

"""
from alembic import op
from alembic_utils.pg_materialized_view import PGMaterializedView

# revision identifiers, used by Alembic.
revision = "985bc36a9cbc"
down_revision = "5bafc336d30d"
branch_labels = None
depends_on = None

view_definition = """
                SELECT id, measure_name, start_date, created_by,
                group1::text, group2::text, group3::text,
                sum, count, count_not_zero, min, max, avg, std,
                median, first_quartile, third_quartile,
                last_updated
                FROM aggregation as agg
                WHERE agg.count >=
                    (SELECT m.aggregation_threshold
                    FROM measure_definition as m
                    WHERE m.name = agg.measure_name)
            """


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    public_filtered_aggregation = PGMaterializedView(
        schema="public",
        signature="filtered_aggregation",
        definition=view_definition,
        with_data=True,
    )

    op.create_entity(public_filtered_aggregation)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_filtered_aggregation = PGMaterializedView(
        schema="public",
        signature="filtered_aggregation",
        definition=view_definition,
        with_data=True,
    )

    op.drop_entity(public_filtered_aggregation)

    # ### end Alembic commands ###
